### ISSUE TITLE
README.md must specify where to store client secrets json file

### ISSUE THREAD

**Issue by tofr** [jchua1/OutofTuneContrabassoonGoonPlatoon#3]

**Comment by lawrenceliu2** [comment]
Fixed, client_secrets.json belongs in the scheduling directory, the same directory as __init__.py

**Comment by tofr** [comment]
Perhaps I am missing something... it appears your readme does not tell a sysadmin installer where to put their client_secrets.json after they have cloned your repo.

**Comment by lawrenceliu2** [comment]
I think #4 in the readme covers it?
